dns: 'DSN=ETL;'
remote_root_directory: 'C:/'
eod_directory: 'EODDataTest/'
from_address: 'noreply@MassStreet.net'
to_address: 'bob@MassStreet.net'
password: 'mh#CdQaUt@Pr48M?'
smtp_server: 'smtp.gmail.com'
smtp_port: 465